key: "validator-1"
genesis: "configs/genesis.devnet.json"

node:
  data_dir: "~/.mononium/data"
  unlock_timeout: 20

network:
  p2p_port: 30333
  rpc_port: 9944
  rest_port: 9933
  bootnodes: []

storage:
  mode: full
  compact_eras: 2
  full_node_rpc: []

mempool:
  max_tx_per_account: 50

log:
  level: info
  json: true
